# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170226_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottompage',
            options={'verbose_name': 'Карта'},
        ),
        migrations.AlterModelOptions(
            name='docspage',
            options={'verbose_name': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='doubletextdoubleimageitem',
            options={'verbose_name': 'Текст с заголовком и двумя изображениями'},
        ),
        migrations.AlterModelOptions(
            name='factspage',
            options={'verbose_name': 'Только факты'},
        ),
        migrations.AlterModelOptions(
            name='faqpage',
            options={'verbose_name': 'Ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='footerpage',
            options={'verbose_name': 'Подвал'},
        ),
        migrations.AlterModelOptions(
            name='forpage',
            options={'verbose_name': 'Для чего применяется'},
        ),
        migrations.AlterModelOptions(
            name='greenpage',
            options={'verbose_name': 'Кому подходит'},
        ),
        migrations.AlterModelOptions(
            name='howpage',
            options={'verbose_name': 'Как применять'},
        ),
        migrations.AlterModelOptions(
            name='imageitem',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='mintpage',
            options={'verbose_name': 'Как работает'},
        ),
        migrations.AlterModelOptions(
            name='orangepage',
            options={'verbose_name': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='textdoubleimageitem',
            options={'verbose_name': '', 'verbose_name_plural': 'Текст с двумя изображениями'},
        ),
        migrations.AlterModelOptions(
            name='textimageitem',
            options={'verbose_name': 'Текст с изображениями', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='toppage',
            options={'verbose_name': 'Верх'},
        ),
        migrations.AlterModelOptions(
            name='whypage',
            options={'verbose_name': 'Почему Актовитдерм'},
        ),
        migrations.AlterModelOptions(
            name='yellowpage',
            options={'verbose_name': 'Отзывы покупателей'},
        ),
        migrations.RemoveField(
            model_name='greenpage',
            name='caption',
        ),
        migrations.AddField(
            model_name='bottompage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='city',
            name='has_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docspage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='factspage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='footerpage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='forpage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='greenpage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='howpage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='mintpage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='orangepage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='toppage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='whypage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AddField(
            model_name='yellowpage',
            name='menu_title',
            field=models.CharField(default='', max_length=255, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='free_delivery_button',
            field=models.ImageField(upload_to='', verbose_name='С бесплатной доставкой'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='items',
            field=models.ManyToManyField(to='base.TextImageItem', verbose_name='Элементы'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='no_delivery_button',
            field=models.ImageField(upload_to='', verbose_name='Без бесплатной доствки'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='textimageitem',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='textimageitem',
            name='order',
            field=models.IntegerField(verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='textimageitem',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='items',
            field=models.ManyToManyField(to='base.TextImageItem', verbose_name='Элементы'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
