# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170305_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='base.City'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('city_selector.html', 'city_selector.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('order_done.html', 'order_done.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
    ]
