# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20170312_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottompage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню'),
        ),
    ]
