# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20170319_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='alt')),
                ('subimage', models.ImageField(upload_to='')),
                ('text', tinymce.models.HTMLField()),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Текст с двумя изображениями',
            },
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='items',
            field=models.ManyToManyField(to='base.GalleryImageItem'),
        ),
    ]
