# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20170319_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя')),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ссылка')),
                ('order', models.IntegerField(verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Текст с изображениями',
                'verbose_name_plural': 'Текст с изображениями',
            },
        ),
    ]
