# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_linkimageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerpage',
            name='items',
            field=models.ManyToManyField(to='base.LinkImageItem'),
        ),
    ]
