# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20170321_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpage',
            name='copy',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
