# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20170321_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='form_header_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок 1й страницы формы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='form_header_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок 2й страницы формы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='form_header_3',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок 3й страницы формы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='form_title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_complete',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст формы'),
        ),
    ]
