# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:55
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20170323_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppage',
            name='text',
        ),
        migrations.AlterField(
            model_name='toppage',
            name='title',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='текст'),
        ),
    ]
