# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20170323_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkimageitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='order_complete',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_caption',
            field=models.CharField(default='E-mail', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='name_caption',
            field=models.CharField(default='Имя и фамилия', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_caption',
            field=models.CharField(default='Телефон', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='items',
            field=models.ManyToManyField(to='base.LinkImageItem', verbose_name='Элемент'),
        ),
    ]
