# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20170326_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='order_complete',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст формы ( шаг 3)'),
        ),
        migrations.AlterField(
            model_name='linkimageitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.FooterPage'),
        ),
    ]
