# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 19:25
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20170329_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimageitem',
            name='subimage',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
