# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 19:26
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20170402_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimageitem',
            name='subimage',
        ),
        migrations.AlterField(
            model_name='galleryimageitem',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
