# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20170402_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='count',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
