# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20170405_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='items',
        ),
        migrations.AddField(
            model_name='textitem',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.FaqPage'),
            preserve_default=False,
        ),
    ]
