# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20170410_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yellowpage',
            name='items',
        ),
        migrations.AddField(
            model_name='tripletextitem',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.YellowPage'),
            preserve_default=False,
        ),
    ]
