# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20170521_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextDoubleImageItem',
        ),
    ]
