# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_kvstore'),
    ]

    operations = [
        #migrations.DeleteModel(
        #    name='KVStore',
        #),
    ]
