# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20170528_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.TextField(verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='count',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.TextField(verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.TextField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='flat',
            field=models.TextField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='house',
            field=models.TextField(verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.TextField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='street',
            field=models.TextField(verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TextField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.TextField(),
        ),
    ]
