# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_city_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='bold',
            field=models.BooleanField(default=False),
        ),
    ]
