# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_city_bold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Телефон'),
        ),
    ]
