# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_sitesettings_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Город')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='metro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='base.Region'),
        ),
    ]
