# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20180103_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottompage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='docspage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='factspage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='footerpage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='forpage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='greenpage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='howpage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='mintpage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='orangepage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='toppage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='whypage',
            name='mobile_template',
        ),
        migrations.RemoveField(
            model_name='yellowpage',
            name='mobile_template',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='modile_site_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bottompage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='template',
            field=models.CharField(blank=True, choices=[('.DS_Store', '.DS_Store'), ('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('choose_city_modal.html', 'choose_city_modal.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('order_form.html', 'order_form.html'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
    ]
