# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20180115_2206'),
        ('base', '0055_auto_20180115_1640'),
    ]

    operations = [
    ]
