# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
                ('free_delivery_button', models.ImageField(upload_to='', verbose_name='Баннер бесплатной доставки')),
                ('no_delivery_button', models.ImageField(upload_to='', verbose_name='Банер  без доставки')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Карта',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Город')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('target', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Target')),
                ('order', models.IntegerField(default=50)),
                ('bold', models.BooleanField(default=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регион',
            },
        ),
        migrations.CreateModel(
            name='DocsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
            ],
            options={
                'verbose_name': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocsPageImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base_mobile.DocsPage')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoubleTextDoubleImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя')),
                ('subimage', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Текст')),
                ('order', models.IntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Как применять',
                'verbose_name_plural': 'Как применять',
            },
        ),
        migrations.CreateModel(
            name='FactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
            ],
            options={
                'verbose_name': 'Только факты',
            },
        ),
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
                ('name_caption', models.CharField(max_length=255)),
                ('mail_caption', models.CharField(max_length=255)),
                ('phone_caption', models.CharField(max_length=255)),
                ('question_caption', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ответы на вопросы',
            },
        ),
        migrations.CreateModel(
            name='FooterPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
                ('caption', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('copy', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Подвал',
            },
        ),
        migrations.CreateModel(
            name='ForPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
            ],
            options={
                'verbose_name': 'Для чего применяется',
            },
        ),
        migrations.CreateModel(
            name='ForPageImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base_mobile.ForPage')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='alt')),
                ('text', tinymce.models.HTMLField()),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Текст с двумя изображениями',
            },
        ),
        migrations.CreateModel(
            name='GreenPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
                ('free_delivery_button', models.ImageField(upload_to='', verbose_name='С бесплатной доставкой')),
                ('no_delivery_button', models.ImageField(upload_to='', verbose_name='Без бесплатной доствки')),
            ],
            options={
                'verbose_name': 'Кому подходит',
            },
        ),
        migrations.CreateModel(
            name='HowPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
                ('caption', tinymce.models.HTMLField()),
                ('items', models.ManyToManyField(to='base_mobile.DoubleTextDoubleImageItem')),
            ],
            options={
                'verbose_name': 'Как применять',
            },
        ),
        migrations.CreateModel(
            name='LinkImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя')),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ссылка')),
                ('order', models.IntegerField(verbose_name='Порядок отображения')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base_mobile.FooterPage')),
            ],
        ),
        migrations.CreateModel(
            name='MintPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
                ('left_image', models.ImageField(upload_to='', verbose_name='Изображение слева')),
                ('right_image', models.ImageField(upload_to='', verbose_name='Изображение справа')),
                ('caption', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Как работает',
            },
        ),
        migrations.CreateModel(
            name='OrangePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
            ],
            options={
                'verbose_name': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(verbose_name='Город')),
                ('total', models.TextField()),
                ('count', models.TextField()),
                ('street', models.TextField(verbose_name='Улица')),
                ('house', models.TextField(verbose_name='Дом')),
                ('flat', models.TextField(verbose_name='Квартира')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('email', models.TextField(verbose_name='Email')),
                ('name', models.TextField(verbose_name='Имя')),
                ('ts', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оформления')),
                ('date', models.TextField(verbose_name='Дата доставки')),
                ('time', models.TextField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Город')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('address', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('metro', models.CharField(max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='base_mobile.City', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('phone', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Телефон')),
                ('meta_description', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ключевые слова')),
                ('cost', models.IntegerField(default=1, verbose_name='Цена')),
                ('form_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок формы')),
                ('form_header_1', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок 1й страницы формы')),
                ('form_header_2', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок 2й страницы формы')),
                ('form_header_3', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок 3й страницы формы')),
                ('order_complete', models.TextField(blank=True, default='', null=True, verbose_name='Текст формы ( шаг 3)')),
                ('const_info', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name_caption', models.CharField(max_length=255)),
                ('mail_caption', models.CharField(max_length=255)),
                ('phone_caption', models.CharField(max_length=255)),
                ('counters', models.TextField(blank=True, default='', null=True, verbose_name='Код Счетчиков')),
                ('yandex_counter_id', models.TextField(blank=True, default='yaCounter44908690', null=True, verbose_name='')),
                ('site_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание')),
                ('mobile_site_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TextImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('order', models.IntegerField(verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Текст с изображениями',
                'verbose_name_plural': 'Текст с изображениями',
            },
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('caption', tinymce.models.HTMLField(verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base_mobile.FaqPage')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='TopPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
                ('backgound', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Фон')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('title', tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='текст')),
                ('banner', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Баннер')),
                ('free_delivery_button', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Баннер бесплатной доставки')),
                ('no_delivery_button', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Баннер без доставки')),
            ],
            options={
                'verbose_name': 'Верх',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Город')),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='base_mobile.City')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='TripleTextItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Имя')),
                ('subtext', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='WhyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
                ('items', models.ManyToManyField(to='base_mobile.TextImageItem', verbose_name='Элементы')),
            ],
            options={
                'verbose_name': 'Почему Актовитдерм',
            },
        ),
        migrations.CreateModel(
            name='YellowPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Изображение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Псевдоним')),
                ('template', models.CharField(blank=True, choices=[('flatpages', 'flatpages'), ('yellow.html', 'yellow.html'), ('facts.html', 'facts.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('index.html', 'index.html'), ('blue.html', 'blue.html'), ('green.html', 'green.html'), ('mint.html', 'mint.html'), ('docs.html', 'docs.html'), ('footer.html', 'footer.html'), ('city_selector.html', 'city_selector.html'), ('page_for.html', 'page_for.html'), ('orange.html', 'orange.html'), ('default.html', 'default.html'), ('order_done.html', 'order_done.html'), ('templates.html', 'templates.html'), ('mobile', 'mobile'), ('admin', 'admin'), ('templates', 'templates'), ('bottom.html', 'bottom.html'), ('faq.html', 'faq.html')], default='', max_length=255, null=True, verbose_name='Шаблон')),
                ('order', models.IntegerField(default=1, verbose_name='Приоритет отображения (порядок)')),
                ('menu_title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название в меню')),
            ],
            options={
                'verbose_name': 'Отзывы покупателей',
            },
        ),
        migrations.AddField(
            model_name='tripletextitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base_mobile.YellowPage'),
        ),
        migrations.AddField(
            model_name='shop',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='base_mobile.Town', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='greenpage',
            name='items',
            field=models.ManyToManyField(to='base_mobile.TextImageItem', verbose_name='Элементы'),
        ),
        migrations.AddField(
            model_name='galleryimageitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base_mobile.OrangePage'),
        ),
        migrations.AddField(
            model_name='factspage',
            name='items',
            field=models.ManyToManyField(to='base_mobile.TextImageItem'),
        ),
    ]
