# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-13 14:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_mobile', '0002_auto_20180113_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimageitem',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='caption',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='caption',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='textimageitem',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='caption',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='textitem',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='tripletextitem',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
