# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_mobile', '0005_auto_20180115_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='order',
            field=models.IntegerField(default='1', verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
