# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-28 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_mobile', '0006_town_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='insta_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='instagramm'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile_site_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='мобильный адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='адрес сайта'),
        ),
    ]
