# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_mobile', '0007_auto_20180128_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottompage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='docspage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='footerpage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='metro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='template',
            field=models.CharField(blank=True, choices=[('order_form.html', 'order_form.html'), ('page_for.html', 'page_for.html'), ('default.html', 'default.html'), ('why.html', 'why.html'), ('top.html', 'top.html'), ('docs.html', 'docs.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('flatpages', 'flatpages'), ('footer.html', 'footer.html'), ('orange.html', 'orange.html'), ('admin', 'admin'), ('choose_city_modal.html', 'choose_city_modal.html'), ('bottom.html', 'bottom.html'), ('mint.html', 'mint.html'), ('city_selector.html', 'city_selector.html'), ('order_done.html', 'order_done.html'), ('blue.html', 'blue.html'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('metro_button_widget.html', 'metro_button_widget.html'), ('green.html', 'green.html')], default='', max_length=255, null=True, verbose_name='Шаблон'),
        ),
    ]
